// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module histoframe_accel_MatStream2AxiStream_2_Pipeline_MMIterOutRow_MMIterOutCol (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        out_mat_data2_dout,
        out_mat_data2_num_data_valid,
        out_mat_data2_fifo_cap,
        out_mat_data2_empty_n,
        out_mat_data2_read,
        ldata1_din,
        ldata1_num_data_valid,
        ldata1_fifo_cap,
        ldata1_full_n,
        ldata1_write,
        bound,
        strideBased_cols_bound_per_npc_V,
        op2_assign,
        last_blk_width_load,
        cols_bound_per_npc_load,
        localbuffer_V_3_out,
        localbuffer_V_3_out_ap_vld,
        filled_V_1_out,
        filled_V_1_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [23:0] out_mat_data2_dout;
input  [1:0] out_mat_data2_num_data_valid;
input  [1:0] out_mat_data2_fifo_cap;
input   out_mat_data2_empty_n;
output   out_mat_data2_read;
output  [127:0] ldata1_din;
input  [1:0] ldata1_num_data_valid;
input  [1:0] ldata1_fifo_cap;
input   ldata1_full_n;
output   ldata1_write;
input  [31:0] bound;
input  [15:0] strideBased_cols_bound_per_npc_V;
input  [31:0] op2_assign;
input  [3:0] last_blk_width_load;
input  [31:0] cols_bound_per_npc_load;
output  [127:0] localbuffer_V_3_out;
output   localbuffer_V_3_out_ap_vld;
output  [7:0] filled_V_1_out;
output   filled_V_1_out_ap_vld;

reg ap_idle;
reg out_mat_data2_read;
reg ldata1_write;
reg localbuffer_V_3_out_ap_vld;
reg filled_V_1_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
reg   [0:0] icmp_ln1027_reg_457;
reg   [0:0] icmp_ln1027_reg_457_pp0_iter2_reg;
reg   [0:0] icmp_ln1027_2_reg_472;
reg    ap_predicate_op45_read_state4;
reg    ap_block_state4_pp0_stage0_iter3;
reg   [0:0] icmp_ln1027_reg_457_pp0_iter3_reg;
reg   [0:0] icmp_ln1027_3_reg_486;
reg    ap_predicate_op66_write_state5;
reg    ap_block_state5_pp0_stage0_iter4;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln1027_fu_202_p2;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    out_mat_data2_blk_n;
wire    ap_block_pp0_stage0;
reg    ldata1_blk_n;
reg    ap_block_pp0_stage0_11001;
wire   [15:0] select_ln1247_fu_221_p3;
reg   [15:0] select_ln1247_reg_461;
wire   [0:0] bLast_fu_237_p2;
reg   [0:0] bLast_reg_467;
wire   [0:0] icmp_ln1027_2_fu_242_p2;
reg   [7:0] filled_V_3_reg_476;
wire   [0:0] icmp_ln1027_3_fu_282_p2;
wire   [8:0] ret_V_1_fu_292_p2;
reg   [8:0] ret_V_1_reg_490;
wire   [6:0] trunc_ln938_fu_298_p1;
reg   [6:0] trunc_ln938_reg_496;
reg    ap_condition_exit_pp0_iter3_stage0;
reg   [7:0] ap_phi_mux_conv3_i12_i_i923_pn_phi_fu_162_p4;
wire   [7:0] or_ln_fu_302_p3;
wire   [7:0] ap_phi_reg_pp0_iter3_conv3_i12_i_i923_pn_reg_159;
wire   [7:0] zext_ln1266_fu_271_p1;
wire   [23:0] ap_phi_reg_pp0_iter0_val_V_1_reg_168;
reg   [23:0] ap_phi_reg_pp0_iter1_val_V_1_reg_168;
reg   [23:0] ap_phi_reg_pp0_iter2_val_V_1_reg_168;
reg   [23:0] ap_phi_reg_pp0_iter3_val_V_1_reg_168;
reg   [23:0] ap_phi_reg_pp0_iter4_val_V_1_reg_168;
reg   [7:0] filled_V_fu_86;
wire   [7:0] filled_next_fu_311_p2;
wire    ap_loop_init;
reg   [127:0] localbuffer_V_fu_90;
wire   [127:0] localbuffer_V_3_fu_380_p3;
wire   [127:0] ret_V_fu_338_p2;
reg   [15:0] j_V_fu_94;
wire   [15:0] add_ln840_fu_247_p2;
reg   [15:0] ap_sig_allocacmp_j_V_load;
reg   [31:0] indvar_flatten_fu_98;
wire   [31:0] add_ln1027_fu_207_p2;
reg    ap_block_pp0_stage0_01001;
wire   [0:0] icmp_ln1027_1_fu_216_p2;
wire   [31:0] zext_ln1027_fu_234_p1;
wire   [3:0] xf_bits_per_clock_fu_261_p3;
wire  signed [4:0] sext_ln1266_fu_267_p1;
wire   [7:0] sub_ln1277_fu_276_p2;
wire   [8:0] zext_ln1496_fu_288_p1;
wire   [127:0] zext_ln1267_fu_325_p1;
wire   [127:0] zext_ln930_fu_329_p1;
wire   [127:0] r_V_3_fu_332_p2;
wire   [6:0] sub_ln553_fu_355_p2;
wire   [127:0] zext_ln930_1_fu_360_p1;
wire   [7:0] trunc_ln455_fu_352_p1;
wire   [127:0] zext_ln948_fu_370_p1;
wire   [0:0] p_Result_s_fu_345_p3;
wire   [127:0] r_V_fu_364_p2;
wire   [127:0] r_V_2_fu_374_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
reg    ap_condition_411;
reg    ap_condition_414;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_done_reg = 1'b0;
end

histoframe_accel_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter3_stage0)) begin
            ap_enable_reg_pp0_iter4 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if (((icmp_ln1027_reg_457 == 1'd0) & (icmp_ln1027_2_fu_242_p2 == 1'd0))) begin
            ap_phi_reg_pp0_iter3_val_V_1_reg_168 <= 24'd0;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter3_val_V_1_reg_168 <= ap_phi_reg_pp0_iter2_val_V_1_reg_168;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        if (((icmp_ln1027_2_reg_472 == 1'd1) & (icmp_ln1027_reg_457_pp0_iter2_reg == 1'd0))) begin
            ap_phi_reg_pp0_iter4_val_V_1_reg_168 <= out_mat_data2_dout;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter4_val_V_1_reg_168 <= ap_phi_reg_pp0_iter3_val_V_1_reg_168;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            filled_V_fu_86 <= 8'd0;
        end else if (((icmp_ln1027_reg_457_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
            filled_V_fu_86 <= filled_next_fu_311_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_98 <= 32'd0;
        end else if (((icmp_ln1027_fu_202_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            indvar_flatten_fu_98 <= add_ln1027_fu_207_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            j_V_fu_94 <= 16'd0;
        end else if (((icmp_ln1027_reg_457 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            j_V_fu_94 <= add_ln840_fu_247_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            localbuffer_V_fu_90 <= 128'd0;
        end else if ((1'b1 == ap_condition_414)) begin
            localbuffer_V_fu_90 <= ret_V_fu_338_p2;
        end else if ((1'b1 == ap_condition_411)) begin
            localbuffer_V_fu_90 <= localbuffer_V_3_fu_380_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
        icmp_ln1027_reg_457 <= icmp_ln1027_fu_202_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        icmp_ln1027_reg_457_pp0_iter2_reg <= icmp_ln1027_reg_457;
        icmp_ln1027_reg_457_pp0_iter3_reg <= icmp_ln1027_reg_457_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_reg_pp0_iter1_val_V_1_reg_168 <= ap_phi_reg_pp0_iter0_val_V_1_reg_168;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_reg_pp0_iter2_val_V_1_reg_168 <= ap_phi_reg_pp0_iter1_val_V_1_reg_168;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln1027_reg_457 == 1'd0))) begin
        bLast_reg_467 <= bLast_fu_237_p2;
        icmp_ln1027_2_reg_472 <= icmp_ln1027_2_fu_242_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        filled_V_3_reg_476 <= filled_V_fu_86;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln1027_reg_457_pp0_iter2_reg == 1'd0))) begin
        icmp_ln1027_3_reg_486 <= icmp_ln1027_3_fu_282_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln1027_reg_457_pp0_iter2_reg == 1'd0) & (icmp_ln1027_3_fu_282_p2 == 1'd0))) begin
        ret_V_1_reg_490 <= ret_V_1_fu_292_p2;
        trunc_ln938_reg_496 <= trunc_ln938_fu_298_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln1027_fu_202_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        select_ln1247_reg_461 <= select_ln1247_fu_221_p3;
    end
end

always @ (*) begin
    if (((icmp_ln1027_fu_202_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (icmp_ln1027_reg_457_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        ap_condition_exit_pp0_iter3_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter3_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((icmp_ln1027_reg_457_pp0_iter2_reg == 1'd0)) begin
        if ((icmp_ln1027_3_fu_282_p2 == 1'd1)) begin
            ap_phi_mux_conv3_i12_i_i923_pn_phi_fu_162_p4 = zext_ln1266_fu_271_p1;
        end else if ((icmp_ln1027_3_fu_282_p2 == 1'd0)) begin
            ap_phi_mux_conv3_i12_i_i923_pn_phi_fu_162_p4 = or_ln_fu_302_p3;
        end else begin
            ap_phi_mux_conv3_i12_i_i923_pn_phi_fu_162_p4 = ap_phi_reg_pp0_iter3_conv3_i12_i_i923_pn_reg_159;
        end
    end else begin
        ap_phi_mux_conv3_i12_i_i923_pn_phi_fu_162_p4 = ap_phi_reg_pp0_iter3_conv3_i12_i_i923_pn_reg_159;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln1027_reg_457 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_sig_allocacmp_j_V_load = add_ln840_fu_247_p2;
    end else begin
        ap_sig_allocacmp_j_V_load = j_V_fu_94;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln1027_reg_457_pp0_iter2_reg == 1'd1))) begin
        filled_V_1_out_ap_vld = 1'b1;
    end else begin
        filled_V_1_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_predicate_op66_write_state5 == 1'b1) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        ldata1_blk_n = ldata1_full_n;
    end else begin
        ldata1_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op66_write_state5 == 1'b1) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        ldata1_write = 1'b1;
    end else begin
        ldata1_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln1027_reg_457_pp0_iter2_reg == 1'd1))) begin
        localbuffer_V_3_out_ap_vld = 1'b1;
    end else begin
        localbuffer_V_3_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_predicate_op45_read_state4 == 1'b1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        out_mat_data2_blk_n = out_mat_data2_empty_n;
    end else begin
        out_mat_data2_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op45_read_state4 == 1'b1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        out_mat_data2_read = 1'b1;
    end else begin
        out_mat_data2_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln1027_fu_207_p2 = (indvar_flatten_fu_98 + 32'd1);

assign add_ln840_fu_247_p2 = (select_ln1247_reg_461 + 16'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((ap_predicate_op66_write_state5 == 1'b1) & (ldata1_full_n == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b1)) | ((ap_predicate_op45_read_state4 == 1'b1) & (out_mat_data2_empty_n == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_predicate_op66_write_state5 == 1'b1) & (ldata1_full_n == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b1)) | ((ap_predicate_op45_read_state4 == 1'b1) & (out_mat_data2_empty_n == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_predicate_op66_write_state5 == 1'b1) & (ldata1_full_n == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b1)) | ((ap_predicate_op45_read_state4 == 1'b1) & (out_mat_data2_empty_n == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b1)));
end

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state4_pp0_stage0_iter3 = ((ap_predicate_op45_read_state4 == 1'b1) & (out_mat_data2_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_state5_pp0_stage0_iter4 = ((ap_predicate_op66_write_state5 == 1'b1) & (ldata1_full_n == 1'b0));
end

always @ (*) begin
    ap_condition_411 = ((icmp_ln1027_3_reg_486 == 1'd0) & (icmp_ln1027_reg_457_pp0_iter3_reg == 1'd0) & (ap_enable_reg_pp0_iter4 == 1'b1));
end

always @ (*) begin
    ap_condition_414 = ((icmp_ln1027_3_reg_486 == 1'd1) & (icmp_ln1027_reg_457_pp0_iter3_reg == 1'd0) & (ap_enable_reg_pp0_iter4 == 1'b1));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

assign ap_phi_reg_pp0_iter0_val_V_1_reg_168 = 'bx;

assign ap_phi_reg_pp0_iter3_conv3_i12_i_i923_pn_reg_159 = 'bx;

always @ (*) begin
    ap_predicate_op45_read_state4 = ((icmp_ln1027_2_reg_472 == 1'd1) & (icmp_ln1027_reg_457_pp0_iter2_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op66_write_state5 = ((icmp_ln1027_3_reg_486 == 1'd0) & (icmp_ln1027_reg_457_pp0_iter3_reg == 1'd0));
end

assign bLast_fu_237_p2 = ((op2_assign == zext_ln1027_fu_234_p1) ? 1'b1 : 1'b0);

assign filled_V_1_out = filled_V_fu_86;

assign filled_next_fu_311_p2 = (ap_phi_mux_conv3_i12_i_i923_pn_phi_fu_162_p4 + filled_V_fu_86);

assign icmp_ln1027_1_fu_216_p2 = ((ap_sig_allocacmp_j_V_load == strideBased_cols_bound_per_npc_V) ? 1'b1 : 1'b0);

assign icmp_ln1027_2_fu_242_p2 = (($signed(zext_ln1027_fu_234_p1) < $signed(cols_bound_per_npc_load)) ? 1'b1 : 1'b0);

assign icmp_ln1027_3_fu_282_p2 = ((sub_ln1277_fu_276_p2 > filled_V_fu_86) ? 1'b1 : 1'b0);

assign icmp_ln1027_fu_202_p2 = ((indvar_flatten_fu_98 == bound) ? 1'b1 : 1'b0);

assign ldata1_din = (r_V_3_fu_332_p2 | localbuffer_V_fu_90);

assign localbuffer_V_3_fu_380_p3 = ((p_Result_s_fu_345_p3[0:0] == 1'b1) ? r_V_fu_364_p2 : r_V_2_fu_374_p2);

assign localbuffer_V_3_out = localbuffer_V_fu_90;

assign or_ln_fu_302_p3 = {{3'd4}, {sext_ln1266_fu_267_p1}};

assign p_Result_s_fu_345_p3 = ret_V_1_reg_490[32'd8];

assign r_V_2_fu_374_p2 = zext_ln1267_fu_325_p1 >> zext_ln948_fu_370_p1;

assign r_V_3_fu_332_p2 = zext_ln1267_fu_325_p1 << zext_ln930_fu_329_p1;

assign r_V_fu_364_p2 = zext_ln1267_fu_325_p1 << zext_ln930_1_fu_360_p1;

assign ret_V_1_fu_292_p2 = (9'd128 - zext_ln1496_fu_288_p1);

assign ret_V_fu_338_p2 = (r_V_3_fu_332_p2 | localbuffer_V_fu_90);

assign select_ln1247_fu_221_p3 = ((icmp_ln1027_1_fu_216_p2[0:0] == 1'b1) ? 16'd0 : ap_sig_allocacmp_j_V_load);

assign sext_ln1266_fu_267_p1 = $signed(xf_bits_per_clock_fu_261_p3);

assign sub_ln1277_fu_276_p2 = ($signed(8'd128) - $signed(zext_ln1266_fu_271_p1));

assign sub_ln553_fu_355_p2 = (7'd0 - trunc_ln938_reg_496);

assign trunc_ln455_fu_352_p1 = ret_V_1_reg_490[7:0];

assign trunc_ln938_fu_298_p1 = ret_V_1_fu_292_p2[6:0];

assign xf_bits_per_clock_fu_261_p3 = ((bLast_reg_467[0:0] == 1'b1) ? last_blk_width_load : 4'd8);

assign zext_ln1027_fu_234_p1 = select_ln1247_reg_461;

assign zext_ln1266_fu_271_p1 = $unsigned(sext_ln1266_fu_267_p1);

assign zext_ln1267_fu_325_p1 = ap_phi_reg_pp0_iter4_val_V_1_reg_168;

assign zext_ln1496_fu_288_p1 = filled_V_fu_86;

assign zext_ln930_1_fu_360_p1 = sub_ln553_fu_355_p2;

assign zext_ln930_fu_329_p1 = filled_V_3_reg_476;

assign zext_ln948_fu_370_p1 = trunc_ln455_fu_352_p1;

endmodule //histoframe_accel_MatStream2AxiStream_2_Pipeline_MMIterOutRow_MMIterOutCol
